GET https://microbloglite.herokuapp.com/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InR3aXR0ZXJmaW5nZXJzIiwiaWF0IjoxNjg3ODA5MTE5LCJleHAiOjE2ODc4OTU1MTl9.CcRQ7OL7EcmizntzUsJNOsHHT9nxvjWpk72XTx1KT-g